# Generated by Django 2.1.4 on 2020-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='feedback',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]