# Generated by Django 2.1.4 on 2020-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershipdetails',
            name='address',
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='subarea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='average_nonPeakHourTraffic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='average_peakHourTraffic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='average_pedestrianDailyCount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='buses_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='cluster_of_hording',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='cost_of_branding_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='cost_per_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='external_Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='force_majeure_clause',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='height_of_gantry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='length_of_gantry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='lit_status',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='printing_and_mounting_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='terms_around_print_mount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='traffic_junction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='width_of_gantry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
