# Generated by Django 2.1.4 on 2020-02-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_auto_20200226_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierhording',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierhording',
            name='signal_waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
