# Generated by Django 2.1.4 on 2020-03-30 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_auto_20200226_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('subarea', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'db_table': 'address_master',
            },
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('supplier_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=70, null=True)),
                ('supplier_type', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supplier_master',
            },
        ),
        migrations.AddField(
            model_name='suppliertypecode',
            name='lower',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecode',
            name='middle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecode',
            name='unit_count_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecode',
            name='upper',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addressmaster',
            name='supplier_id',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='v0.SupplierMaster'),
        ),
    ]
