# Generated by Django 2.1.4 on 2020-03-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0003_remove_proposalinfo_brand_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='brand_organisation_id',
            field=models.IntegerField(default=11),
        ),
    ]
