# Generated by Django 2.1.4 on 2020-05-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0003_whatsappgroupinventory_whatsappindividualinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_id', models.CharField(max_length=50)),
                ('supplier_type', models.CharField(max_length=3)),
                ('society', models.ForeignKey(db_column='society_id', on_delete=django.db.models.deletion.CASCADE, to='v0.SupplierTypeSociety')),
            ],
            options={
                'db_table': 'supplier_relationship',
            },
        ),
        migrations.AlterUniqueTogether(
            name='supplierrelationship',
            unique_together={('society', 'supplier_id')},
        ),
    ]
