# Generated by Django 2.1.4 on 2020-05-20 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0003_whatsappgroupinventory_whatsappindividualinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRetailShopMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('retail_shop', models.ForeignKey(db_column='retail_shop_id', on_delete=django.db.models.deletion.CASCADE, to='v0.SupplierTypeRetailShop')),
                ('society', models.ForeignKey(db_column='society_id', on_delete=django.db.models.deletion.CASCADE, to='v0.SupplierTypeSociety')),
            ],
            options={
                'db_table': 'supplier_retail_shop_mapping',
            },
        ),
        migrations.AlterUniqueTogether(
            name='supplierretailshopmapping',
            unique_together={('society', 'retail_shop')},
        ),
    ]
