# Generated by Django 2.1.4 on 2020-02-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0003_auto_20200226_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinfo',
            name='brand',
            field=models.CharField(blank=True, choices=[('single_brand', 'single_brand'), ('multi_brand', 'multi_brand')], max_length=10, null=True),
        ),
    ]
