# Generated by Django 2.1.4 on 2020-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0004_shortlistedspaces_brand_organisation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedspaces',
            name='brand_organisation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
