# Generated by Django 2.1.4 on 2020-03-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0005_auto_20200303_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemapping',
            name='comments',
            field=models.TextField(blank=True, db_column='COMMENTS', null=True),
        ),
    ]
