# Generated by Django 2.1.4 on 2020-03-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_auto_20200226_0941'),
        ('v0', '0006_auto_20200302_1226'),
    ]

    operations = [
    ]
