# Generated by Django 2.1.4 on 2020-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0010_auto_20200407_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliertypecode',
            old_name='unit_count_type',
            new_name='unit_primary_count',
        ),
        migrations.RemoveField(
            model_name='ownershipdetails',
            name='food_tasting',
        ),
        migrations.AddField(
            model_name='addressmaster',
            name='nearest_landmark',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='alternate_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ownershipdetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecode',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecode',
            name='unit_secondary_count',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecode',
            name='unit_tertiary_count',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
