# Generated by Django 2.1.4 on 2020-04-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0011_auto_20200408_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliermaster',
            old_name='unit_count',
            new_name='unit_primary_count',
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='unit_secondary_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='unit_tertiary_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
