# Generated by Django 2.1.4 on 2020-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0012_auto_20200409_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalinfo',
            name='brand',
            field=models.CharField(blank=True, choices=[('single_brand', 'single_brand'), ('multi_brand', 'multi_brand')], max_length=60, null=True),
        ),
    ]
