# Generated by Django 2.1.4 on 2020-04-10 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0013_auto_20200410_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierHordings',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('supplier_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('locality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('machadalo_index', models.CharField(blank=True, max_length=30, null=True)),
                ('address1', models.CharField(blank=True, max_length=252, null=True)),
                ('address2', models.CharField(blank=True, max_length=252, null=True)),
                ('area', models.CharField(blank=True, max_length=252, null=True)),
                ('subarea', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=252, null=True)),
                ('state', models.CharField(blank=True, max_length=252, null=True)),
                ('zipcode', models.IntegerField(blank=True, max_length=252, null=True)),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0.0, max_length=252, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=252, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=252, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=32, null=True)),
                ('account_number', models.CharField(blank=True, max_length=252, null=True)),
                ('food_tasting_allowed', models.BooleanField(default=False, null=True)),
                ('sales_allowed', models.BooleanField(default=False, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('length_of_gantry', models.IntegerField(blank=True, null=True)),
                ('width_of_gantry', models.IntegerField(blank=True, null=True)),
                ('height_of_gantry', models.IntegerField(blank=True, null=True)),
                ('force_majeure_clause', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True)),
                ('terms_around_print_mount', models.IntegerField(blank=True, null=True)),
                ('cost_per_sqft', models.IntegerField(blank=True, null=True)),
                ('cost_of_branding_space', models.IntegerField(blank=True, null=True)),
                ('printing_and_mounting_cost', models.IntegerField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster_of_hording', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True)),
                ('traffic_junction', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('average_peakHourTraffic', models.CharField(blank=True, max_length=255, null=True)),
                ('average_nonPeakHourTraffic', models.CharField(blank=True, max_length=255, null=True)),
                ('average_pedestrianDailyCount', models.CharField(blank=True, max_length=255, null=True)),
                ('lit_status', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True)),
                ('buses_count', models.IntegerField(blank=True, null=True)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('signal_waiting_time', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_hording',
            },
        ),
        migrations.RemoveField(
            model_name='supplierhording',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suppliertypebusshelter',
            name='average_footfall_daily_count',
        ),
        migrations.RemoveField(
            model_name='suppliertypecorporate',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='suppliertypecorporate',
            name='totalemployees_count',
        ),
        migrations.RemoveField(
            model_name='suppliertypegym',
            name='footfall_weekend',
        ),
        migrations.RemoveField(
            model_name='suppliertyperetailshop',
            name='average_weekday',
        ),
        migrations.RemoveField(
            model_name='suppliertyperetailshop',
            name='average_weekend',
        ),
        migrations.RemoveField(
            model_name='suppliertypesalon',
            name='footfall_week',
        ),
        migrations.RemoveField(
            model_name='suppliertypesalon',
            name='footfall_weekend',
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='account_number',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='address1',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='address2',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='area',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='bank_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='city',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='food_tasting_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='sales_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='state',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='subarea',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliereducationalinstitute',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='account_number',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='address1',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='address2',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='area',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='bank_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='city',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='food_tasting_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='sales_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='state',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='subarea',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='account_number',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='address1',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='address2',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='area',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='bank_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='city',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='food_tasting_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='sales_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='state',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='subarea',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='account_number',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='address1',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='address2',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='area',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='bank_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='city',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='food_tasting_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='sales_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='state',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='subarea',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='account_number',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='address1',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='address2',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='area',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='bank_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='city',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='food_tasting_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='sales_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='state',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='subarea',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='account_number',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='address1',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='address2',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='area',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='bank_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='city',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='sales_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='state',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='subarea',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='account_number',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='address1',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='address2',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='area',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='bank_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='city',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='food_tasting_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='sales_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='state',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='subarea',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=252, null=True),
        ),
        migrations.DeleteModel(
            name='SupplierHording',
        ),
    ]
