# Generated by Django 2.1.4 on 2020-04-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0013_auto_20200410_1122'),
        ('v0', '0013_auto_20200410_1639'),
    ]

    operations = [
    ]
