# Generated by Django 2.1.4 on 2020-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0014_auto_20200410_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='average_down_boarding_daily_count',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='average_on_boarding_daily_count',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        )
    ]
