# Generated by Django 2.1.4 on 2020-04-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0014_merge_20200410_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierHording',
            new_name='SupplierHordings',
        ),
    ]
