# Generated by Django 2.1.4 on 2020-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0015_auto_20200410_1852'),
    ]

    operations = [
    ]
