# Generated by Django 2.1.4 on 2020-04-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0015_auto_20200410_1852'),
        ('v0', '0014_auto_20200410_1838'),
    ]

    operations = [
    ]
