# Generated by Django 2.1.4 on 2020-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0016_merge_20200411_1011'),
    ]

    operations = [

        migrations.AlterField(
            model_name='supplierhording',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='address1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='food_tasting_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='sales_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='subarea',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplierhording',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
