# Generated by Django 2.1.4 on 2020-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0017_auto_20200411_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='external_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
