# Generated by Django 2.1.4 on 2020-04-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0018_auto_20200411_1031'),
    ]

    operations = [
    ]
