# Generated by Django 2.1.4 on 2020-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0019_auto_20200413_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_footfall_daily_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_non_peak_hour_traffic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_peak_hour_traffic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='direction',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
