# Generated by Django 2.1.4 on 2020-04-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0020_auto_20200416_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliertypebusshelter',
            name='average_footfall_daily_count',
        ),
        migrations.RemoveField(
            model_name='suppliertypebusshelter',
            name='average_non_peak_hour_traffic',
        ),
        migrations.RemoveField(
            model_name='suppliertypebusshelter',
            name='average_peak_hour_traffic',
        ),
        migrations.RemoveField(
            model_name='suppliertypebusshelter',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='suppliertypebusshelter',
            name='direction',
        ),
    ]
