# Generated by Django 2.1.4 on 2020-04-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0021_auto_20200416_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysummary',
            name='billing_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='bus_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='bus_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='bus_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='bus_shelter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='bus_shelter_lit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='bus_wrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='ceiling_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='counter_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='floor_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='gantry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='gantry_lit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='hoarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='hoarding_lit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='table_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='tent_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='wall_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
