# Generated by Django 2.1.4 on 2020-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0022_auto_20200421_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaster',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='subarea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
