# Generated by Django 2.1.4 on 2020-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0024_auto_20200427_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='assigned_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shortlistedspaces',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortlistedspaces',
            name='permission_box_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortlistedspaces',
            name='receipt_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='feedback',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
