# Generated by Django 2.1.4 on 2020-04-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0025_auto_20200427_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncomments',
            name='shortlisted_spaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.ShortlistedSpaces'),
        ),
    ]
