# Generated by Django 2.1.4 on 2020-05-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0026_auto_20200428_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='average_down_boarding_daily_count',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='average_on_boarding_daily_count',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='halt_buses_count',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='lit_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
