# Generated by Django 2.1.4 on 2020-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0027_auto_20200506_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaster',
            name='quality_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
