# Generated by Django 2.1.4 on 2020-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0028_suppliermaster_quality_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaster',
            name='locality_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
