# Generated by Django 2.1.4 on 2020-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0032_auto_20200520_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysummary',
            name='banner_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='banner_medium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='banner_small',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='poster_allowed_lift_A3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='poster_allowed_lift_A4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='stall_customize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='standee_large',
            field=models.BooleanField(default=False),
        ),
    ]
