# Generated by Django 2.1.4 on 2020-06-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0034_proposalinfo_is_mix'),
        ('v0', '0005_auto_20200601_1309'),
    ]

    operations = [
    ]
