# Generated by Django 2.1.4 on 2020-06-24 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0034_proposalinfo_is_mix'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'booking_status',
            },
        ),
        migrations.CreateModel(
            name='BookingSubstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('booking_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.BookingStatus')),
            ],
            options={
                'db_table': 'booking_substatus',
            },
        ),
        migrations.CreateModel(
            name='TypeOfEndCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_of_end_customer',
            },
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='type_of_end_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.TypeOfEndCustomer'),
        ),
    ]
