# Generated by Django 2.1.4 on 2020-06-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0035_auto_20200624_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinfo',
            name='type_of_end_customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='v0.TypeOfEndCustomer'),
        ),
    ]
