# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0035_auto_20161020_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTypeGym',
            fields=[
                ('supplier_id', models.CharField(max_length=20, serialize=False, primary_key=True)),
                ('supplier_code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=70, null=True, blank=True)),
                ('address1', models.CharField(max_length=250, null=True, blank=True)),
                ('address2', models.CharField(max_length=250, null=True, blank=True)),
                ('area', models.CharField(max_length=255, null=True, blank=True)),
                ('subarea', models.CharField(max_length=30, null=True, blank=True)),
                ('city', models.CharField(max_length=250, null=True, blank=True)),
                ('state', models.CharField(max_length=250, null=True, blank=True)),
                ('zipcode', models.IntegerField(null=True, blank=True)),
                ('latitude', models.FloatField(default=0.0, null=True, blank=True)),
                ('longitude', models.FloatField(default=0.0, null=True, blank=True)),
                ('locality_rating', models.CharField(max_length=50, null=True, blank=True)),
                ('quality_rating', models.CharField(max_length=50, null=True, blank=True)),
                ('machadalo_index', models.CharField(max_length=30, null=True, blank=True)),
                ('gym_type', models.CharField(max_length=30, null=True, blank=True)),
                ('category', models.CharField(max_length=30, null=True, blank=True)),
                ('gym_type_chain', models.CharField(max_length=30, null=True, blank=True)),
                ('chain_origin', models.CharField(max_length=30, null=True, blank=True)),
                ('totalmembership_perannum', models.IntegerField(null=True, blank=True)),
                ('footfall_day', models.IntegerField(null=True, blank=True)),
                ('footfall_weekend', models.IntegerField(null=True, blank=True)),
                ('advertising_media', models.CharField(max_length=30, null=True, blank=True)),
                ('dietchart_price', models.IntegerField(null=True, blank=True)),
                ('stall_price_day', models.IntegerField(null=True, blank=True)),
                ('stall_price_two_day', models.IntegerField(null=True, blank=True)),
                ('standee_price_week', models.IntegerField(null=True, blank=True)),
                ('standee_price_two_week', models.IntegerField(null=True, blank=True)),
                ('standee_price_month', models.IntegerField(null=True, blank=True)),
                ('standee_places', models.IntegerField(null=True, blank=True)),
                ('standee_location', models.CharField(max_length=30, null=True, blank=True)),
                ('banner_price_week', models.IntegerField(null=True, blank=True)),
                ('banner_price_month', models.IntegerField(null=True, blank=True)),
                ('banner_places', models.IntegerField(null=True, blank=True)),
                ('banner_location', models.CharField(max_length=30, null=True, blank=True)),
                ('flyer_price_month', models.IntegerField(null=True, blank=True)),
                ('flyer_distribution', models.CharField(max_length=30, null=True, blank=True)),
                ('poster_price_week', models.IntegerField(null=True, blank=True)),
                ('poster_price_month', models.IntegerField(null=True, blank=True)),
                ('poster_places', models.IntegerField(null=True, blank=True)),
                ('mirrorstrip_count', models.IntegerField(null=True, blank=True)),
                ('mirrorstrip_price_week', models.IntegerField(null=True, blank=True)),
                ('mirrorstrip_price_month', models.IntegerField(null=True, blank=True)),
                ('locker_count', models.IntegerField(null=True, blank=True)),
                ('locker_price_week', models.IntegerField(null=True, blank=True)),
                ('locker_price_month', models.IntegerField(null=True, blank=True)),
                ('wall_price_month', models.IntegerField(null=True, blank=True)),
                ('wall_price_three_month', models.IntegerField(null=True, blank=True)),
                ('gym_name', models.CharField(max_length=30, null=True, blank=True)),
                ('bank_name', models.CharField(max_length=30, null=True, blank=True)),
                ('ifsc_code', models.CharField(max_length=30, null=True, blank=True)),
                ('account_number', models.CharField(max_length=30, null=True, blank=True)),
            ],
            options={
                'db_table': 'supplier_gym',
            },
        ),
        migrations.CreateModel(
            name='SupplierTypeSalon',
            fields=[
                ('supplier_id', models.CharField(max_length=20, serialize=False, primary_key=True)),
                ('supplier_code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=70, null=True, blank=True)),
                ('address1', models.CharField(max_length=250, null=True, blank=True)),
                ('address2', models.CharField(max_length=250, null=True, blank=True)),
                ('area', models.CharField(max_length=255, null=True, blank=True)),
                ('subarea', models.CharField(max_length=30, null=True, blank=True)),
                ('city', models.CharField(max_length=250, null=True, blank=True)),
                ('state', models.CharField(max_length=250, null=True, blank=True)),
                ('zipcode', models.IntegerField(null=True, blank=True)),
                ('latitude', models.FloatField(default=0.0, null=True, blank=True)),
                ('longitude', models.FloatField(default=0.0, null=True, blank=True)),
                ('locality_rating', models.CharField(max_length=50, null=True, blank=True)),
                ('quality_rating', models.CharField(max_length=50, null=True, blank=True)),
                ('machadalo_index', models.CharField(max_length=30, null=True, blank=True)),
                ('salon_type', models.CharField(max_length=30, null=True, db_column='SALON_TYPE', blank=True)),
                ('category', models.CharField(max_length=30, null=True, db_column='CATEGORY', blank=True)),
                ('salon_type_chain', models.CharField(max_length=30, null=True, db_column='SALON_TYPE_CHAIN', blank=True)),
                ('footfall_day', models.IntegerField(null=True, db_column='FOOTFALL_DAY', blank=True)),
                ('footfall_week', models.IntegerField(null=True, db_column='FOOTFALL_WEEK', blank=True)),
                ('footfall_weekend', models.IntegerField(null=True, db_column='FOOTFALL_WEEKEND', blank=True)),
                ('isspaavailable', models.BooleanField(default=False, db_column='ISSPAAVAILABLE')),
                ('advertising_media', models.CharField(max_length=30, null=True, db_column='AD_MEDIA', blank=True)),
                ('shop_size', models.CharField(max_length=30, null=True, db_column='SHOP_SIZE', blank=True)),
                ('floor_size', models.CharField(max_length=30, null=True, db_column='FLOOR_SIZE', blank=True)),
                ('standee_price_week', models.IntegerField(null=True, db_column='ST_PRICE_WEEK', blank=True)),
                ('standee_price_weekend', models.IntegerField(null=True, db_column='ST_PRICE_WEEKEND', blank=True)),
                ('standee_places', models.IntegerField(null=True, db_column='ST_PLACES', blank=True)),
                ('standee_location', models.IntegerField(null=True, db_column='ST_LOCATION', blank=True)),
                ('banner_price_week', models.IntegerField(null=True, db_column='BA_PRICE_WEEK', blank=True)),
                ('banner_price_weekend', models.IntegerField(null=True, db_column='BA_PRICE_WEEKEND', blank=True)),
                ('banner_places', models.IntegerField(null=True, db_column='BA_PLACES', blank=True)),
                ('banner_location', models.IntegerField(null=True, db_column='BA_LOCATION', blank=True)),
                ('flyer_price_week', models.IntegerField(null=True, db_column='FL_PRICE_WEEK', blank=True)),
                ('flyer_distribution', models.IntegerField(null=True, db_column='FL_DISTRIBUTION', blank=True)),
                ('poster_price_week', models.IntegerField(null=True, db_column='PO_PRICE_WEEK', blank=True)),
                ('poster_price_weekend', models.IntegerField(null=True, db_column='PO_PRICE_WEEKEND', blank=True)),
                ('poster_places', models.IntegerField(null=True, db_column='PO_PLACES', blank=True)),
                ('mirrorstrip_price_week', models.IntegerField(null=True, db_column='MS_PRICE_WEEK', blank=True)),
                ('mirrorstrip_price_month', models.IntegerField(null=True, db_column='MS_PRICE_MONTH', blank=True)),
                ('salon_name', models.CharField(max_length=30, null=True, db_column='SALON_NAME', blank=True)),
                ('bank_name', models.CharField(max_length=30, null=True, db_column='BANK_NAME', blank=True)),
                ('ifsc_code', models.CharField(max_length=30, null=True, db_column='IFSC_CODE', blank=True)),
                ('account_number', models.CharField(max_length=30, null=True, db_column='ACCOUNT_NUMBER', blank=True)),
            ],
            options={
                'db_table': 'supplier_salon',
            },
        ),
    ]
