# Generated by Django 2.1.4 on 2020-07-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0035_merge_20200619_0716'),
        ('v0', '0036_auto_20200630_1503'),
    ]

    operations = [
    ]
