# Generated by Django 2.1.4 on 2020-06-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0036_proposalinfo_type_of_end_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='bk_substatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.BookingSubstatus'),
        ),
        migrations.AddField(
            model_name='shortlistedspaces',
            name='bk_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.BookingStatus'),
        ),
    ]
