# Generated by Django 2.1.4 on 2020-06-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0037_auto_20200626_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsubstatus',
            name='booking_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_substatus', to='v0.BookingStatus'),
        ),
    ]
