# Generated by Django 2.1.4 on 2020-07-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0039_auto_20200708_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaster',
            name='quantity_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
