# Generated by Django 2.1.4 on 2020-07-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0040_suppliermaster_quantity_rating'),
        ('v0', '0039_auto_20200723_1404'),
    ]

    operations = [
    ]
