# Generated by Django 2.1.4 on 2020-08-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0041_merge_20200724_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
