# Generated by Django 2.1.4 on 2020-08-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0041_merge_20200723_0900'),
        ('v0', '0041_merge_20200724_1022'),
    ]

    operations = [
    ]
