# Generated by Django 2.1.4 on 2020-08-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0041_merge_20200724_1022'),
        ('v0', '0041_merge_20200723_0900'),
    ]

    operations = [
    ]
