# Generated by Django 2.1.4 on 2020-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0042_contactdetails_relationship_status'),
        ('v0', '0041_merge_20200723_0900'),
    ]

    operations = [
    ]
