# Generated by Django 2.1.4 on 2020-08-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0043_supplierbus_suppliergantry_supplierradiochannel_suppliertvchannel'),
        ('v0', '0043_merge_20200804_0904'),
    ]

    operations = [
    ]
