# Generated by Django 2.1.4 on 2020-08-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0042_merge_20200804_0533'),
        ('v0', '0044_merge_20200804_1630'),
    ]

    operations = [
    ]
