# Generated by Django 2.1.4 on 2020-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0045_merge_20200805_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='requirement_given',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='shortlistedspaces',
            name='requirement_given_date',
            field=models.DateTimeField(null=True),
        ),
    ]
