# Generated by Django 2.1.4 on 2020-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0046_auto_20200828_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='ac_hault',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_non_peak_hour_traffic',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_peak_hour_traffic',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='bus_shelter_road_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='bus_shelter_supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='bus_shelters_cluster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='cost',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='cost_sqft',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='direction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='footfall_daily_count',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='force_majeure_clause',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='population_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='print_cost',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='size_bottom',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='size_middle',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='size_side_ext',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='size_side_int',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='size_top',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='terms_print_mount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='total_size',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='type_bus_stand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='type_road_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
