# Generated by Django 2.1.4 on 2020-09-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0047_auto_20200907_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='business_subtype',
            field=models.ManyToManyField(to='v0.BusinessSubTypes'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='business_type',
            field=models.ManyToManyField(to='v0.BusinessTypes'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_subtype', to='v0.BusinessSubTypes'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='v0.BusinessTypes'),
        ),
    ]
