# Generated by Django 2.1.4 on 2020-09-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0049_requirement'),
        ('v0', '0048_auto_20200911_1640'),
    ]

    operations = [
    ]
