# Generated by Django 2.1.4 on 2020-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0052_auto_20200911_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='preferred_company',
        ),
        migrations.AddField(
            model_name='requirement',
            name='preferred_company',
            field=models.ManyToManyField(blank=True, null=True, related_name='preferred', to='v0.Organisation'),
        ),
    ]
