# Generated by Django 2.1.4 on 2020-09-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0053_auto_20200911_1125'),
        ('v0', '0050_merge_20200911_1119'),
    ]

    operations = [
    ]
