# Generated by Django 2.1.4 on 2020-09-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0055_auto_20200911_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_deleted',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=5),
        ),
    ]
