# Generated by Django 2.1.4 on 2020-09-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0056_requirement_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='lead_status',
            field=models.CharField(choices=[('Very Deep Lead', 'Very Deep Lead'), ('Deep Lead', 'Deep Lead'), ('Hot Lead', 'Hot Lead'), ('Lead', 'Lead'), ('Raw Lead', 'Raw Lead')], default='Deep Lead', max_length=30),
        ),
    ]
