# Generated by Django 2.1.4 on 2020-09-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0057_auto_20200919_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='color_code',
            field=models.IntegerField(null=True),
        ),
    ]
