# Generated by Django 2.1.4 on 2020-09-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0058_shortlistedspaces_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedspaces',
            name='color_code',
            field=models.IntegerField(default=4, null=True),
        ),
    ]
