# Generated by Django 2.1.4 on 2020-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0059_auto_20200921_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='varified',
            new_name='varified_bd',
        ),
        migrations.AddField(
            model_name='requirement',
            name='varified_ops',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=5),
        ),
    ]
