# Generated by Django 2.1.4 on 2020-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0062_auto_20201003_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='terms_print_mount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='floor_size',
            field=models.IntegerField(blank=True, db_column='FLOOR_SIZE', null=True),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='shop_size',
            field=models.IntegerField(blank=True, db_column='SHOP_SIZE', null=True),
        ),
    ]
