# Generated by Django 2.1.4 on 2020-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0063_auto_20201006_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='current_patner_feedback',
            field=models.CharField(choices=[('NA', 'NA'), ('Satisfied', 'Satisfied'), ('Dissatisfied', 'Dissatisfied'), ('Extremely Dissatisfied', 'Extremely Dissatisfied')], default='NA', max_length=5),
        ),
        migrations.AddField(
            model_name='requirement',
            name='current_patner_feedback_reason',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_current_patner',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=5),
        ),
    ]
