# Generated by Django 2.1.4 on 2020-10-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0064_auto_20201007_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='current_patner_feedback',
            field=models.CharField(choices=[('NA', 'NA'), ('Satisfied', 'Satisfied'), ('Dissatisfied', 'Dissatisfied'), ('Extremely Dissatisfied', 'Extremely Dissatisfied')], default='NA', max_length=50),
        ),
    ]
