# Generated by Django 2.1.4 on 2020-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0068_auto_20201013_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='current_company_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='l1_answers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='l2_answers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='preferred_company_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
