# Generated by Django 2.1.4 on 2020-10-21 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0069_auto_20201019_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='varified_ops_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
