# Generated by Django 2.1.4 on 2020-10-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0070_requirement_varified_ops_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='varified_ops_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
