# Generated by Django 2.1.4 on 2020-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0072_auto_20201027_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='change_current_patner',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=5),
        ),
    ]
