# Generated by Django 2.1.4 on 2020-11-12 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0075_auto_20201106_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='company_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_campaign', to='v0.ProposalInfo'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='company_shortlisted_spaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_shortlisted_spaces', to='v0.ShortlistedSpaces'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='impl_timeline',
            field=models.CharField(choices=[('within 2 weeks', 'within 2 weeks'), ('within 2 months', 'within 2 months'), ('2 months to 6 months', '2 months to 6 months'), ('6 months to 1 year', '6 months to 1 year'), ('1 year to 1.5 years', '1 year to 1.5 years'), ('yet not decided', 'yet not decided')], default='within 2 months', max_length=30),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='meating_timeline',
            field=models.CharField(choices=[('as soon as possible', 'as soon as possible'), ('within 1 week', 'within 1 week'), ('within a month', 'within a month'), ('after a month', 'after a month')], default='within 1 week', max_length=30),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='varified_ops_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varified_ops_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
