# Generated by Django 2.1.4 on 2020-11-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0033_shortlistedspaces_last_call_date'),
        ('v0', '0076_auto_20201112_1703'),
    ]

    operations = [
    ]
