# Generated by Django 2.1.4 on 2020-11-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0077_merge_20201119_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='impl_timeline',
            field=models.CharField(choices=[('within 2 weeks', 'within 2 weeks'), ('within 2 months', 'within 2 months'), ('2 months to 6 months', '2 months to 6 months'), ('6 months to 1 year', '6 months to 1 year'), ('1 year to 1.5 years', '1 year to 1.5 years'), ('yet not decided', 'yet not decided'), ('not given', 'not given')], default='within 2 months', max_length=30),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='meating_timeline',
            field=models.CharField(choices=[('as soon as possible', 'as soon as possible'), ('within 1 week', 'within 1 week'), ('within a month', 'within a month'), ('after a month', 'after a month'), ('not given', 'not given')], default='within 1 week', max_length=30),
        ),
    ]
