# Generated by Django 2.1.4 on 2020-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0079_auto_20201123_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='call_back_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
