# Generated by Django 2.1.4 on 2020-12-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0080_requirement_call_back_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='lead_purchased',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='requirement',
            name='purchased_date',
            field=models.DateTimeField(null=True),
        ),
    ]
