# Generated by Django 2.1.4 on 2020-12-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0082_auto_20201210_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequirement',
            name='call_back_preference',
            field=models.CharField(choices=[('anytime', 'anytime'), ('no need of call. arrange a meeting directly', 'no need of call. arrange a meeting directly'), ('weekday morning', 'weekday morning'), ('weekday evening', 'weekday evening'), ('weekend morning', 'weekend morning'), ('weekend evening', 'weekend evening'), ('customized calling period', 'customized calling period')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='call_back_preference',
            field=models.CharField(choices=[('anytime', 'anytime'), ('no need of call. arrange a meeting directly', 'no need of call. arrange a meeting directly'), ('weekday morning', 'weekday morning'), ('weekday evening', 'weekday evening'), ('weekend morning', 'weekend morning'), ('weekend evening', 'weekend evening'), ('customized calling period', 'customized calling period')], default='NA', max_length=100),
        ),
    ]
