# Generated by Django 2.1.4 on 2021-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0085_requirement_is_preferred_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='hotness_of_lead',
            field=models.CharField(choices=[('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H5', 'H5'), ('H6', 'H6')], default='H1', max_length=5),
        ),
    ]
