# Generated by Django 2.1.4 on 2021-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0086_requirement_hotness_of_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequirement',
            name='lead_purchased',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='lead_purchased',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=5),
        ),
    ]
