# Generated by Django 2.1.4 on 2021-01-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0089_auto_20210128_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='v0.Organisation'),
        ),
    ]
