# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 08:27
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0091_suppliertypesociety_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypesociety',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypesociety',
            name='supplier_status',
            field=models.CharField(choices=[(b'Tapped', b'Tapped'), (b'LetterGiven', b'LetterGiven'), (b'MeetingRequired', b'MeetingRequired'), (b'Other', b'Other')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='corporateparkcompanylist',
            name='name',
            field=models.CharField(blank=True, db_column=b'COMPANY_NAME', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='shortlistedspaces',
            table=None,
        ),
    ]
