# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0092_auto_20180725_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('campaign_id', models.CharField(blank=True, max_length=70, null=True)),
                ('leads_form_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'leads_form',
            },
        ),
        migrations.CreateModel(
            name='LeadsFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('supplier_id', models.CharField(blank=True, max_length=70, null=True)),
                ('item_order_id', models.IntegerField(null=True)),
                ('item_value', models.CharField(blank=True, max_length=200, null=True)),
                ('leads_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.LeadsForm')),
            ],
            options={
                'db_table': 'leads_form_data',
            },
        ),
        migrations.CreateModel(
            name='LeadsFormItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('key_name', models.CharField(blank=True, max_length=70, null=True)),
                ('key_options', models.CharField(blank=True, max_length=200, null=True)),
                ('key_type', models.CharField(choices=[('STRING', 'STRING'), ('BOOLEAN', 'BOOLEAN'), ('INT', 'INT'), ('EMAIL', 'EMAIL'), ('PASSWORD', 'PASSWORD'), ('PHONE', 'PHONE'), ('RADIO', 'RADIO'), ('DROPDOWN', 'DROPDOWN'), ('CHECKBOX', 'CHECKBOX'), ('TEXTAREA', 'TEXTAREA')], max_length=70, null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=70, null=True)),
                ('leads_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.LeadsForm')),
            ],
            options={
                'db_table': 'leads_form_items',
            },
        ),
        migrations.AlterUniqueTogether(
            name='campaignleads',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='campaignleads',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.RemoveField(
            model_name='societyleads',
            name='society',
        ),
        migrations.DeleteModel(
            name='CampaignLeads',
        ),
        migrations.DeleteModel(
            name='SocietyLeads',
        ),
    ]
