# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0093_auto_20180815_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsform',
            name='last_entry_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leadsformdata',
            name='entry_id',
            field=models.IntegerField(null=True),
        ),
    ]
