# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0095_auto_20180816_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadsformdata',
            old_name='item_order_id',
            new_name='item_id',
        ),
    ]
