# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0098_hashtagimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsform',
            name='status',
            field=models.CharField(choices=[(b'ACTIVE', b'ACTIVE'), (b'INACTIVE', b'INACTIVE')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='leadsformdata',
            name='status',
            field=models.CharField(choices=[(b'ACTIVE', b'ACTIVE'), (b'INACTIVE', b'INACTIVE')], max_length=70, null=True),
        ),
    ]
