# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0100_leadsform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('campaign_id', models.CharField(blank=True, max_length=70, null=True)),
                ('checklist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[(b'ACTIVE', b'ACTIVE'), (b'INACTIVE', b'INACTIVE')], max_length=70, null=True)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='ChecklistColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('key_name', models.CharField(blank=True, max_length=70, null=True)),
                ('key_options', models.CharField(blank=True, max_length=200, null=True)),
                ('key_type', models.CharField(choices=[(b'STRING', b'STRING'), (b'BOOLEAN', b'BOOLEAN'), (b'INT', b'INT'), (b'EMAIL', b'EMAIL'), (b'PASSWORD', b'PASSWORD'), (b'PHONE', b'PHONE'), (b'RADIO', b'RADIO'), (b'DROPDOWN', b'DROPDOWN'), (b'CHECKBOX', b'CHECKBOX'), (b'TEXTAREA', b'TEXTAREA')], max_length=70, null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[(b'ACTIVE', b'ACTIVE'), (b'INACTIVE', b'INACTIVE')], max_length=70, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.LeadsForm')),
            ],
            options={
                'db_table': 'checklist_columns',
            },
        ),
        migrations.CreateModel(
            name='ChecklistRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('list_item', models.CharField(blank=True, max_length=70, null=True)),
                ('item_id', models.CharField(blank=True, max_length=70, null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('parent_id', models.IntegerField()),
                ('level', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[(b'ACTIVE', b'ACTIVE'), (b'INACTIVE', b'INACTIVE')], max_length=70, null=True)),
                ('assignee', models.CharField(blank=True, max_length=70, null=True)),
                ('assigned_time', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Checklist')),
            ],
            options={
                'db_table': 'checklist_rows',
            },
        ),
    ]
