# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0101_checklist_checklistcolumns_checklistrows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistrows',
            name='assigned_time',
        ),
        migrations.RemoveField(
            model_name='checklistrows',
            name='assignee',
        ),
    ]
