# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0102_auto_20180819_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('supplier_id', models.CharField(blank=True, max_length=70, null=True)),
                ('item_value', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_id', models.IntegerField(null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[(b'ACTIVE', b'ACTIVE'), (b'INACTIVE', b'INACTIVE')], max_length=70, null=True)),
            ],
            options={
                'db_table': 'checklist_data',
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_type',
            field=models.CharField(choices=[(b'CAMPAIGN', b'CAMPAIGN'), (b'SUPPLIER', b'SUPPLIER')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='last_entry_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='checklistcolumns',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Checklist'),
        ),
        migrations.AddField(
            model_name='checklistdata',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Checklist'),
        ),
    ]
