# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0103_auto_20180819_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsform',
            name='fields_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
