# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0104_leadsform_fields_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='transaction_or_check_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
