# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 17:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0105_shortlistedspaces_transaction_or_check_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='SupplierPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('phase_no', models.CharField(blank=True, default=b'', max_length=10, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.ProposalInfo')),
            ],
            options={
                'db_table': 'supplier_phase',
            },
        ),
        migrations.AddField(
            model_name='leadsformdata',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='leadsformitems',
            name='hot_lead_criteria',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='checklistcolumns',
            name='key_type',
            field=models.CharField(choices=[(b'STRING', b'STRING'), (b'BOOLEAN', b'BOOLEAN'), (b'INT', b'INT'), (b'EMAIL', b'EMAIL'), (b'PASSWORD', b'PASSWORD'), (b'PHONE', b'PHONE'), (b'RADIO', b'RADIO'), (b'DROPDOWN', b'DROPDOWN'), (b'CHECKBOX', b'CHECKBOX'), (b'TEXTAREA', b'TEXTAREA'), (b'FLOAT', b'FLOAT'), (b'DATE', b'DATE')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='leadsformitems',
            name='key_type',
            field=models.CharField(choices=[(b'STRING', b'STRING'), (b'BOOLEAN', b'BOOLEAN'), (b'INT', b'INT'), (b'EMAIL', b'EMAIL'), (b'PASSWORD', b'PASSWORD'), (b'PHONE', b'PHONE'), (b'RADIO', b'RADIO'), (b'DROPDOWN', b'DROPDOWN'), (b'CHECKBOX', b'CHECKBOX'), (b'TEXTAREA', b'TEXTAREA'), (b'FLOAT', b'FLOAT'), (b'DATE', b'DATE')], max_length=70, null=True),
        ),
        migrations.AlterModelTable(
            name='shortlistedspaces',
            table='shortlisted_spaces',
        ),
        migrations.AddField(
            model_name='shortlistedspaces',
            name='phase_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.SupplierPhase'),
        ),
    ]
