# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0106_supplierphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='phase_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.SupplierPhase'),
        ),
    ]
