# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0107_shortlistedspaces_phase_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shortlistedspaces',
            table='shortlisted_spaces',
        ),
    ]
