# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0109_auto_20180901_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistcolumns',
            name='key_type',
            field=models.CharField(choices=[(b'STRING', b'STRING'), (b'BOOLEAN', b'BOOLEAN'), (b'INT', b'INT'), (b'EMAIL', b'EMAIL'), (b'PASSWORD', b'PASSWORD'), (b'PHONE', b'PHONE'), (b'RADIO', b'RADIO'), (b'DROPDOWN', b'DROPDOWN'), (b'CHECKBOX', b'CHECKBOX'), (b'TEXTAREA', b'TEXTAREA'), (b'FLOAT', b'FLOAT'), (b'DATE', b'DATE')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='leadsformitems',
            name='key_type',
            field=models.CharField(choices=[(b'STRING', b'STRING'), (b'BOOLEAN', b'BOOLEAN'), (b'INT', b'INT'), (b'EMAIL', b'EMAIL'), (b'PASSWORD', b'PASSWORD'), (b'PHONE', b'PHONE'), (b'RADIO', b'RADIO'), (b'DROPDOWN', b'DROPDOWN'), (b'CHECKBOX', b'CHECKBOX'), (b'TEXTAREA', b'TEXTAREA'), (b'FLOAT', b'FLOAT'), (b'DATE', b'DATE')], max_length=70, null=True),
        ),
    ]
