# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0109_auto_20180901_1241'),
    ]

    operations = [
    ]
