# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0109_auto_20180901_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistcolumns',
            name='key_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('BOOLEAN', 'BOOLEAN'), ('INT', 'INT'), ('EMAIL', 'EMAIL'), ('PASSWORD', 'PASSWORD'), ('PHONE', 'PHONE'), ('RADIO', 'RADIO'), ('DROPDOWN', 'DROPDOWN'), ('CHECKBOX', 'CHECKBOX'), ('TEXTAREA', 'TEXTAREA'), ('FLOAT', 'FLOAT'), ('DATE', 'DATE')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='leadsformitems',
            name='key_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('BOOLEAN', 'BOOLEAN'), ('INT', 'INT'), ('EMAIL', 'EMAIL'), ('PASSWORD', 'PASSWORD'), ('PHONE', 'PHONE'), ('RADIO', 'RADIO'), ('DROPDOWN', 'DROPDOWN'), ('CHECKBOX', 'CHECKBOX'), ('TEXTAREA', 'TEXTAREA'), ('FLOAT', 'FLOAT'), ('DATE', 'DATE')], max_length=70, null=True),
        ),
    ]
