# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0110_merge_20180906_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsformitems',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
