# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0111_auto_20180909_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedspaces',
            name='phase_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='v0.SupplierPhase'),
        ),
    ]
