# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0106_auto_20180906_1712'),
        ('v0', '0112_leadsformitems_supplier_id'),
        ('v0', '0110_auto_20180906_0501'),
    ]

    operations = [
    ]
