# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0112_auto_20180911_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsform',
            name='hot_lead_criteria',
            field=models.IntegerField(null=True),
        ),
    ]
