# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0113_leadsform_hot_lead_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsform',
            name='hot_lead_criteria',
        ),
    ]
