# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0115_auto_20180916_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='organisation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='v0.Organisation'),
            preserve_default=False,
        ),
    ]
