# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0116_activitylog_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsFormContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('contact_id', models.IntegerField(null=True)),
                ('contact_name', models.CharField(blank=True, max_length=70, null=True)),
                ('contact_mobile', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'leads_form_contacts',
            },
        ),
        migrations.AddField(
            model_name='leadsform',
            name='last_contact_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leadsformcontacts',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.LeadsForm'),
        ),
    ]
