# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0117_auto_20180919_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadsformcontacts',
            old_name='form_id',
            new_name='form',
        ),
        migrations.RemoveField(
            model_name='leadsformcontacts',
            name='contact_id',
        ),
    ]
