# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0118_auto_20180919_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='last_entry_id',
            new_name='last_row_id',
        ),
        migrations.RenameField(
            model_name='checklistcolumns',
            old_name='item_id',
            new_name='column_id',
        ),
        migrations.RenameField(
            model_name='checklistcolumns',
            old_name='key_name',
            new_name='column_name',
        ),
        migrations.RenameField(
            model_name='checklistcolumns',
            old_name='key_options',
            new_name='column_options',
        ),
        migrations.RenameField(
            model_name='checklistcolumns',
            old_name='key_type',
            new_name='column_type',
        ),
        migrations.RenameField(
            model_name='checklistdata',
            old_name='item_value',
            new_name='cell_value',
        ),
        migrations.RenameField(
            model_name='checklistdata',
            old_name='entry_id',
            new_name='column_id',
        ),
        migrations.RenameField(
            model_name='checklistdata',
            old_name='item_id',
            new_name='row_id',
        ),
    ]
