# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0120_auto_20180920_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_template',
            field=models.BooleanField(null=True),
        ),
    ]
