# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0121_checklist_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsFormSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('supplier_id', models.CharField(blank=True, max_length=70, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=70, null=True)),
                ('total_leads_count', models.IntegerField(null=True)),
                ('hot_leads_count', models.IntegerField(null=True)),
                ('hot_leads_percentage', models.IntegerField(null=True)),
                ('leads_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.LeadsForm')),
            ],
            options={
                'db_table': 'leads_form_summary',
            },
        ),
        migrations.AlterField(
            model_name='checklist',
            name='is_template',
            field=models.BooleanField(),
        ),
    ]
