# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0122_auto_20180924_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsformsummary',
            name='hot_leads_percentage',
            field=models.FloatField(null=True),
        ),
    ]
