# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0123_auto_20180924_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinfo',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
