# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0124_proposalinfo_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='freebies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
