# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0125_shortlistedspaces_freebies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadalias',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='LeadAlias',
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
