# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 08:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0127_shortlistedinventorycomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=70, null=True)),
                ('inventory_type', models.CharField(blank=True, choices=[('POSTER', 'Poster'), ('STANDEE', 'Standee'), ('STALL', 'Stall'), ('CAR DISPLAY', 'Car Display'), ('FLIER', 'Flier'), ('BANNER', 'Banner'), ('POSTER LIFT', 'Poster Lift'), ('GLASS_FACADE', 'GLASS_FACADE'), ('HOARDING', 'HOARDING'), ('DROPDOWN', 'DROPDOWN'), ('STANDEE', 'STANDEE'), ('PROMOTION_DESK', 'PROMOTION_DESK'), ('PILLAR', 'PILLAR'), ('TROLLEY', 'TROLLEY'), ('WALL_INVENTORY', 'WALL_INVENTORY'), ('FLOOR_INVENTORY', 'FLOOR_INVENTORY'), ('GATEWAY ARCH', 'GATEWAY ARCH')], db_column='inventory_type', max_length=20, null=True)),
                ('related_to', models.CharField(blank=True, choices=[('BOOKING', 'BOOKING'), ('EXECUTION', 'EXECUTION')], db_column='related_to', max_length=20, null=True)),
                ('shortlisted_spaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.ShortlistedSpaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_comments',
            },
        ),
        migrations.RemoveField(
            model_name='shortlistedinventorycomments',
            name='shortlisted_inventory_details',
        ),
        migrations.RemoveField(
            model_name='shortlistedinventorycomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShortlistedInventoryComments',
        ),
    ]
