# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0128_auto_20181005_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncomments',
            name='shortlisted_spaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.ShortlistedSpaces'),
            preserve_default=False,
        ),
    ]
