# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0130_suppliertypesociety_relationship_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='landline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
