# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0132_auto_20181012_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='user_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('ADMIN', 'ADMIN')], default='NORMAL', max_length=70, null=True),
        )
    ]
