# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0133_auto_20181023_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsformsummary',
            name='leads_form',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LeadsFormSummary',
        ),
    ]
