# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0134_auto_20181113_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='stall_locations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
