# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-12 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0136_shortlistedinventorypricingdetails_inventory_number_of_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistcolumns',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='checklistdata',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='checklistrows',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='leadsformcontacts',
            name='form',
        ),
        migrations.RemoveField(
            model_name='leadsformdata',
            name='leads_form',
        ),
        migrations.RemoveField(
            model_name='leadsformitems',
            name='leads_form',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistColumns',
        ),
        migrations.DeleteModel(
            name='ChecklistData',
        ),
        migrations.DeleteModel(
            name='ChecklistRows',
        ),
        migrations.DeleteModel(
            name='LeadsForm',
        ),
        migrations.DeleteModel(
            name='LeadsFormContacts',
        ),
        migrations.DeleteModel(
            name='LeadsFormData',
        ),
        migrations.DeleteModel(
            name='LeadsFormItems',
        ),
    ]
