# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0137_auto_20181212_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='booking_priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shortlistedspaces',
            name='cost_per_flat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
