# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-21 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('v0', '0138_auto_20181213_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunBoardInventory',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('id', models.AutoField(db_column=b'ID', primary_key=True, serialize=False)),
                ('adinventory_id', models.CharField(db_column=b'ADINVENTORY_ID', max_length=22, unique=True)),
                ('object_id', models.CharField(max_length=20, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'sun_board_inventory',
            },
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='sun_board_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='sun_board_breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='sun_board_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='sun_board_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adinventorylocationmapping',
            name='adinventory_name',
            field=models.CharField(choices=[(b'POSTER', b'Poster'), (b'STANDEE', b'Standee'), (b'STALL', b'Stall'), (b'CAR DISPLAY', b'Car Display'), (b'FLIER', b'Flier'), (b'BANNER', b'Banner'), (b'POSTER LIFT', b'Poster Lift'), (b'GLASS_FACADE', b'GLASS_FACADE'), (b'HOARDING', b'HOARDING'), (b'DROPDOWN', b'DROPDOWN'), (b'STANDEE', b'STANDEE'), (b'PROMOTION_DESK', b'PROMOTION_DESK'), (b'PILLAR', b'PILLAR'), (b'TROLLEY', b'TROLLEY'), (b'WALL_INVENTORY', b'WALL_INVENTORY'), (b'FLOOR_INVENTORY', b'FLOOR_INVENTORY'), (b'GATEWAY ARCH', b'GATEWAY ARCH'), (b'SUNBOARD', b'SUNBOARD'), (b'BANNER', b'BANNER')], db_column=b'ADINVENTORY_NAME', default=b'POSTER', max_length=10),
        ),
        migrations.AlterField(
            model_name='adinventorytype',
            name='adinventory_name',
            field=models.CharField(choices=[(b'POSTER', b'Poster'), (b'STANDEE', b'Standee'), (b'STALL', b'Stall'), (b'CAR DISPLAY', b'Car Display'), (b'FLIER', b'Flier'), (b'BANNER', b'Banner'), (b'POSTER LIFT', b'Poster Lift'), (b'GLASS_FACADE', b'GLASS_FACADE'), (b'HOARDING', b'HOARDING'), (b'DROPDOWN', b'DROPDOWN'), (b'STANDEE', b'STANDEE'), (b'PROMOTION_DESK', b'PROMOTION_DESK'), (b'PILLAR', b'PILLAR'), (b'TROLLEY', b'TROLLEY'), (b'WALL_INVENTORY', b'WALL_INVENTORY'), (b'FLOOR_INVENTORY', b'FLOOR_INVENTORY'), (b'GATEWAY ARCH', b'GATEWAY ARCH'), (b'SUNBOARD', b'SUNBOARD'), (b'BANNER', b'BANNER')], db_column=b'ADINVENTORY_NAME', default=b'POSTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaigncomments',
            name='inventory_type',
            field=models.CharField(blank=True, choices=[(b'POSTER', b'Poster'), (b'STANDEE', b'Standee'), (b'STALL', b'Stall'), (b'CAR DISPLAY', b'Car Display'), (b'FLIER', b'Flier'), (b'BANNER', b'Banner'), (b'POSTER LIFT', b'Poster Lift'), (b'GLASS_FACADE', b'GLASS_FACADE'), (b'HOARDING', b'HOARDING'), (b'DROPDOWN', b'DROPDOWN'), (b'STANDEE', b'STANDEE'), (b'PROMOTION_DESK', b'PROMOTION_DESK'), (b'PILLAR', b'PILLAR'), (b'TROLLEY', b'TROLLEY'), (b'WALL_INVENTORY', b'WALL_INVENTORY'), (b'FLOOR_INVENTORY', b'FLOOR_INVENTORY'), (b'GATEWAY ARCH', b'GATEWAY ARCH'), (b'SUNBOARD', b'SUNBOARD'), (b'BANNER', b'BANNER')], db_column=b'inventory_type', max_length=20, null=True),
        ),
    ]
