# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('v0', '0139_auto_20181221_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinventory',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='bannerinventory',
            name='object_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
