# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-22 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0140_auto_20181221_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='sunboard_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
