# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0141_shortlistedspaces_sunboard_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypesociety',
            name='flat_count_type',
            field=models.IntegerField(blank=True, choices=[(1, '0-149'), (2, '150-399'), (3, '400+')], null=True),
        ),
    ]
