# Generated by Django 2.1.4 on 2019-01-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0143_auto_20190114_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinfo',
            name='principal_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.Organisation'),
        ),
    ]
