# Generated by Django 2.1.4 on 2019-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0144_proposalinfo_principal_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncomments',
            name='campaign_id',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='hashtagimages',
            name='object_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proposalinfo',
            name='proposal_id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shortlistedspaces',
            name='object_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinfo',
            name='supplier_id',
            field=models.CharField(db_column='SUPPLIER_ID', db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliertypebusdepot',
            name='supplier_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliertypebusshelter',
            name='supplier_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliertypecorporate',
            name='supplier_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliertypegym',
            name='supplier_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='supplier_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliertypesalon',
            name='supplier_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliertypesociety',
            name='supplier_id',
            field=models.CharField(db_column='SUPPLIER_ID', db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
