# Generated by Django 2.1.4 on 2019-02-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0145_auto_20190124_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='created_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.Organisation'),
        ),
    ]
