# Generated by Django 2.1.4 on 2019-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0145_auto_20190124_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertypesociety',
            name='flat_count_type',
            field=models.CharField(blank=True, choices=[('1-150', '1-150'), ('151-400', '151-400'), ('401+', '401+')], max_length=50, null=True),
        ),
    ]
