# Generated by Django 2.1.4 on 2019-02-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0147_auto_20190206_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalinfo',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proposalinfo',
            name='updated_by',
            field=models.CharField(max_length=50),
        ),
    ]
