# Generated by Django 2.1.4 on 2019-03-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0149_auto_20190222_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncomments',
            name='related_to',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL')], db_column='related_to', max_length=20, null=True),
        ),
    ]
