# Generated by Django 2.1.4 on 2019-04-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0149_auto_20190222_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v0.Organisation'),
        ),
    ]
