# Generated by Django 2.1.4 on 2019-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0152_supplierassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='banner_allowed',
            field=models.BooleanField(db_column='BANNER_ALLOWED', default=False),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='name_for_payment',
            field=models.CharField(blank=True, db_column='NAME_FOR_PAYMENT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='poster_allowed_lift',
            field=models.BooleanField(db_column='POSTER_ALLOWED_LIFT', default=False),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='poster_allowed_nb',
            field=models.BooleanField(db_column='POSTER_ALLOWED_NB', default=False),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='relationship_manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='stall_allowed',
            field=models.BooleanField(db_column='STALL_ALLOWED', default=False),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='standee_allowed',
            field=models.BooleanField(db_column='STANDEE_ALLOWED', default=False),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='supplier_status',
            field=models.CharField(choices=[('Tapped', 'Tapped'), ('LetterGiven', 'LetterGiven'), ('MeetingRequired', 'MeetingRequired'), ('Other', 'Other')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='tower_count',
            field=models.IntegerField(blank=True, db_column='TOWER_COUNT', null=True),
        ),
        migrations.AlterField(
            model_name='pricemappingdefault',
            name='supplier',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
