# Generated by Django 2.1.4 on 2019-04-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0153_auto_20190419_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemappingdefault',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='SUPPLIER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_prices', to='v0.SupplierTypeSociety'),
        ),
    ]
