# Generated by Django 2.1.4 on 2019-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0154_auto_20190424_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtagimages',
            name='object_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
