# Generated by Django 2.1.4 on 2019-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0155_auto_20190523_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='booking_sub_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
