# Generated by Django 2.1.4 on 2019-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0156_shortlistedspaces_booking_sub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedspaces',
            name='next_action_date',
            field=models.DateTimeField(null=True),
        ),
    ]
