# Generated by Django 2.1.4 on 2019-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0157_baseuser_emailverifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='emailVerifyDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
