# Generated by Django 2.1.4 on 2020-01-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0158_baseuser_emailverifydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='average_weekday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='average_weekend',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='contact_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='contact_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='country_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='feedback',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='mobile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='salutation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='std_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='store_size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
