# Generated by Django 2.1.4 on 2020-02-12 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0161_auto_20200110_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierEducationalInstitute',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=utc), editable=False)),
                ('supplier_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('subarea', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('locality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('machadalo_index', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=250, null=True)),
                ('food_tasting_allowed', models.BooleanField(default=False)),
                ('sales_allowed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_educational_institute',
            },
        ),
        migrations.AlterField(
            model_name='suppliertyperetailshop',
            name='retail_shop_type',
            field=models.CharField(blank=True, choices=[('Toy Store', 'Toy Store'), ('Sports Goods', 'Sports Goods'), ('Electronic Goods', 'Electronic Goods'), ('Sanitary Goods', 'Sanitary Goods'), ('Grocery Goods', 'Grocery Goods'), ('Stationery Goods', 'Stationery Goods'), ('Merchandise Goods', 'Merchandise Goods'), ('Mobile Store', 'Mobile Store'), ('Mixed Store', 'Mixed Store'), ('Hypermart', 'Hypermart'), ('Jewelry Store', 'Jewelry Store'), ('Auto Dealership Store', 'Auto Dealership Store'), ('Shoes Store', 'Shoes Store'), ('Mall', 'Mall'), ('Gaming Zone', 'Gaming Zone'), ('FND (Food & Dining)', 'FND (Food & Dining)')], max_length=255, null=True),
        ),
    ]
