# Generated by Django 2.1.4 on 2020-02-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0162_auto_20200212_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypecorporate',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertyperetailshop',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
