# Generated by Django 2.1.4 on 2020-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0163_auto_20200214_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypesociety',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
