# Generated by Django 2.1.4 on 2020-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0165_auto_20200214_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecompanydetails',
            name='employeeCount',
            field=models.IntegerField(blank=True, db_column='EMPLOYEE_COUNT', null=True),
        ),
    ]
