# Generated by Django 2.1.4 on 2020-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0166_corporatecompanydetails_employeecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatecompanydetails',
            name='employeeCount',
        ),
        migrations.AddField(
            model_name='corporateparkcompanylist',
            name='employeeCount',
            field=models.IntegerField(blank=True, db_column='EMPLOYEE_COUNT', null=True),
        ),
    ]
