# Generated by Django 2.1.4 on 2020-02-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0170_auto_20200219_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipdetails',
            name='end_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ownershipdetails',
            name='start_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
