# Generated by Django 2.1.4 on 2020-02-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0171_auto_20200220_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='type',
            field=models.CharField(blank=True, choices=[('RS', 'RS'), ('CP', 'CP'), ('GY', 'GY'), ('SA', 'SA'), ('BS', 'BS'), ('RE', 'RE'), ('EI', 'EI')], max_length=10, null=True),
        ),
    ]
