# Generated by Django 2.1.4 on 2020-02-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0172_amenity_type'),
        ('v0', '0162_auto_20200212_1044'),
        ('v0', '0162_auto_20200218_0505'),
    ]

    operations = [
    ]
