# Generated by Django 2.1.4 on 2020-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0173_merge_20200221_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_down_boarding_daily_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_footfall_daily_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_non_peak_hour_traffic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_on_boarding_daily_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='average_peak_hour_traffic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliertypebusshelter',
            name='external_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
