# Generated by Django 2.1.4 on 2020-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0175_supplierhording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(blank=True, db_column='EVENT_NAME', max_length=255, null=True),
        ),
    ]
